apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mainframe-mock
  namespace: argocd
  labels:
    app: mainframe-mock
    component: application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amir1824/bank-gitops.git
    targetRevision: main
    path: charts/mainframe-mock
    helm:
      releaseName: mainframe-mock
      values: |
        replicaCount: 1
        image:
          repository: python
          tag: "3.9"
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: 8080
        route:
          enabled: true
          tls:
            enabled: true
            termination: edge
            insecureEdgeTerminationPolicy: Redirect
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: mizrahi-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Health assessment
  ignoreDifferences:
    - group: route.openshift.io
      kind: Route
      jsonPointers:
        - /status/ingress
